eb_application:
  name: "my-eb-application"
  region: us-east-1
  beanstalk_envs:
    "my-eb-env-a"
    "my-eb-env-b"

command:
  display: "Check External Network Connectivity"
  document: "remote_server_connectivity_test"
  hash: "12345678901234567890123456789012345678901234567890"
  s3bucket: "my-output-bucket"
  s3keyprefix: "myprefix"
